services:
  web:
    build: .
    container_name: library_service_api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db_ls
      - redis

  redis:
    image: redis:7
    container_name: redis_ls
    ports:
      - "6379:6379"

  db_ls:
    image: postgres:14-alpine
    container_name: postgres_db_ls
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}

  celery_worker:
    build: .
    container_name: library_celery_worker
    command: celery -A library_service_api worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis
      - db_ls
    env_file:
      - .env

  celery_beat:
    build: .
    container_name: library_celery_beat
    command: celery -A library_service_api beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db_ls
    env_file:
      - .env

volumes:
  postgres_db: